### PR TITLE
Add keys items and logic to tasks

### PR DESCRIPTION
**Pull request by CodeWithDennis**

### CODE REVIEW

**Comment by CodeWithDennis** [comment]
Since I can only do my main area quests, all my keys start with "KV" (Kiu Vongsa). But sometimes, there are other keys like KV Doc, NT Doc, PL Doc (Medical Detective Quest Line). Maybe we could include an extra option for keys that lists similar keys, containing keys that are the same but for a different area. Then when hovering over the key it will do a little popup with this info? @robertarnorsson

**Comment by robertarnorsson** [comment]
What about just adding each key for each faction. And change the key parameter from the task to the objective.

**Comment by CodeWithDennis** [comment]
> What about just adding each key for each faction. And change the key parameter from the task to the objective.

Yea that's probably better, I had this at first but changed it back😅

**Comment by CodeWithDennis** [comment]
As we talked about, we'll use plain images without any words on them, and then we'll add a special name label on top using a custom component. This way we don't need all the keys with different names.

**Comment by CodeWithDennis** [comment]
Copied to another branch

**Pull request closed without merging**
